# Предобработка и анализ данных о видеоиграх

- Автор: Гуляев Илья
- Дата: 22.01.2026

### Цели и задачи проекта

Цель проекта - изучить развитие игровой индустрии в период ее расцвета (2000-2013 года).

Перед нами стоят следующие задачи:
- изучить данные о продажах игр и популярности игровых платформ;
- изучить региональные предпочтения игроков;
- изучить оценки игроков и критиков

### Описание данных

Данные `/datasets/new_games.csv` содержат информацию о продажах игр разных жанров и платформ, а также пользовательские и экспертные оценки игр:
- `Name` — название игры.
- `Platform` — название платформы.
- `Year of Release` — год выпуска игры.
- `Genre` — жанр игры.
- `NA sales` — продажи в Северной Америке (в миллионах проданных копий).
- `EU sales` — продажи в Европе (в миллионах проданных копий).
- `JP sales` — продажи в Японии (в миллионах проданных копий).
- `Other sales` — продажи в других странах (в миллионах проданных копий).
- `Critic Score` — оценка критиков (от 0 до 100).
- `User Score` — оценка пользователей (от 0 до 10).
- `Rating` — рейтинг организации ESRB (англ. Entertainment Software Rating Board). Эта ассоциация определяет рейтинг компьютерных игр и присваивает им подходящую возрастную категорию.

### Содержимое проекта

Наша задача — познакомиться с данными, проверить их корректность и провести предобработку, получив необходимый срез данных.

Перед анализом вам необходимо дополнительно сделать следующее:
- предварительно изучить данные и удостовериься в том, что они соответсвуют описанию
- привести названия столбцов к формату "snake case"
- оптимизировать типы данных
- обработать пропущенные значения
- обработать дубликаты

---

## 1. Загрузка данных и знакомство с ними

- Загрузите необходимые библиотеки Python и данные датасета `/datasets/new_games.csv`.

- Познакомьтесь с данными: выведите первые строки и результат метода `info()`.

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('/datasets/new_games.csv')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16956 entries, 0 to 16955
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16954 non-null  object
 1   Platform         16956 non-null  object
 2   Year of Release  16681 non-null  float64
 3   Genre            16954 non-null  object
 4   NA sales         16956 non-null  float64
 5   EU sales         16956 non-null  object
 6   JP sales         16956 non-null  object
 7   Other sales      16956 non-null  float64
 8   Critic Score     8242 non-null   float64
 9   User Score       10152 non-null  object
 10  Rating           10085 non-null  object
dtypes: float64(4), object(7)
memory usage: 1.4+ MB


В предоставленном датафрейме 16956 строк и 11 столбцов, он занимает 1.4+ мб оперативной памяти.

Датафрейм соответствует описанию.

В датафрейме встречаются пропуски в столбцах:
- `Name`
- `Year of Release`
- `Genre`
- `Critic Score`
- `User Score`
- `Rating`

В следующих стобцах типы данных неверны:
- `Year of Release` тип данных float64, нужно использовать datetime64
- `EU sales` тип данных object, нужно использовать int64
- `JP sales` тип данных object, нужно использовать int64
- `User Score` тип данных object, нужно использовать float64

Навзвание столбца `Rating` неоднозначно, лучше использовать `age_rating`.

Названия сотальных столбцов необходимо привести к "sake case" - все буквы в нижнем регистре, для разделения использовать нижнее подчеркивание "_"

---

## 2.  Проверка ошибок в данных и их предобработка


### 2.1. Названия, или метки, столбцов датафрейма

- Выведите на экран названия всех столбцов датафрейма и проверьте их стиль написания.
- Приведите все столбцы к стилю snake case. Названия должны быть в нижнем регистре, а вместо пробелов — подчёркивания.

In [7]:
df.columns # выводим названия всех столбцов

Index(['Name', 'Platform', 'Year of Release', 'Genre', 'NA sales', 'EU sales',
       'JP sales', 'Other sales', 'Critic Score', 'User Score', 'Rating'],
      dtype='object')

In [8]:
df.columns = df.columns.str.lower().str.replace(' ','_') # меняем стиль написания на snake case
df = df.rename(columns = {'rating': 'age_rating'}) # изменияем название столбца rating

In [9]:
df.columns # проверяем новые названия столбцов

Index(['name', 'platform', 'year_of_release', 'genre', 'na_sales', 'eu_sales',
       'jp_sales', 'other_sales', 'critic_score', 'user_score', 'age_rating'],
      dtype='object')

### 2.2. Типы данных

- Если встречаются некорректные типы данных, предположите их причины.
- При необходимости проведите преобразование типов данных. Помните, что столбцы с числовыми данными и пропусками нельзя преобразовать к типу `int64`. Сначала вам понадобится обработать пропуски, а затем преобразовать типы данных.

In [10]:
df['user_score'] = pd.to_numeric(df['user_score'], errors='coerce')
df['eu_sales'] = pd.to_numeric(df['eu_sales'], errors='coerce')
df['eu_sales'] = pd.to_numeric(df['user_score'], errors='coerce')
df['jp_sales'] = pd.to_numeric(df['jp_sales'], errors='coerce') 
# преобразовываем типы данных к наиболее подходящим

In [11]:

df['year_of_release'] = pd.to_datetime(df['year_of_release'],format='%Y')
# преобразовываем к типу данных для работы с датами

In [12]:
df.info() # проверяем преобразование

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16956 entries, 0 to 16955
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16954 non-null  object
 1   platform         16956 non-null  object
 2   year_of_release  16681 non-null  datetime64[ns]
 3   genre            16954 non-null  object
 4   na_sales         16956 non-null  float64
 5   eu_sales         7688 non-null   float64
 6   jp_sales         16952 non-null  float64
 7   other_sales      16956 non-null  float64
 8   critic_score     8242 non-null   float64
 9   user_score       7688 non-null   float64
 10  age_rating       10085 non-null  object
dtypes: datetime64[ns](1), float64(6), object(4)
memory usage: 1.4+ MB

In [13]:
df_shape_1 = df.shape[0] # сохраняем изначальное кол-во строк в датафрейме

Мы преоразовали типы данных по плану. Некорректные типы данных возникли из-за наличия в столбцах строковых значений.

### 2.3. Наличие пропусков в данных

- Посчитайте количество пропусков в каждом столбце в абсолютных и относительных значениях.

In [14]:
df.isna().sum() # подсчитываем количество пропусков

name                  2
platform              0
year_of_release     275
genre                 2
na_sales              0
eu_sales           9268
jp_sales              4
other_sales           0
critic_score       8714
user_score         9268
age_rating         6871
dtype: int64

In [15]:
round(df.isna().sum() / len(df) * 100, 2) # подсчитываем процент пропусков

name                0.01
platform            0.00
year_of_release     1.62
genre               0.01
na_sales            0.00
eu_sales           54.66
jp_sales            0.02
other_sales         0.00
critic_score       51.39
user_score         54.66
age_rating         40.52
dtype: float64

In [16]:
def na_func(c):
        return round(c.isna().sum() / len(c) * 100,2)
    # функция для подсчета процента пропусков

In [17]:
df_with_na_share = df.groupby('platform').agg(na_func)
df_with_na_share # считаем кол-во пропусков в разрезе каждой платформы

,name,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,age_rating
platform,,,,,,,,,,
2600,0.0,12.59,0.0,0.0,100.00,0.00,0.0,100.00,100.00,100.00
3DO,0.0,0.00,0.0,0.0,100.00,0.00,0.0,100.00,100.00,100.00
3DS,0.0,1.51,0.0,0.0,66.98,0.00,0.0,68.11,66.98,56.23
DC,0.0,0.00,0.0,0.0,73.08,0.00,0.0,73.08,73.08,73.08
DS,0.0,1.38,0.0,0.0,76.02,0.05,0.0,66.74,76.02,40.97
GB,0.0,1.02,0.0,0.0,100.00,0.00,0.0,100.00,100.00,100.00
GBA,0.0,1.31,0.0,0.0,69.18,0.00,0.0,47.07,69.18,36.80
GC,0.0,2.49,0.0,0.0,34.28,0.00,0.0,19.54,34.28,15.81
GEN,6.9,0.00,6.9,0.0,100.00,0.00,0.0,100.00,100.00,100.00
GG,0.0,0.00,0.0,0.0,100.00,0.00,0.0,100.00,100.00,100.00
N64,0.0,0.93,0.0,0.0,100.00,0.00,0.0,100.00,100.00,100.00
NES,0.0,0.00,0.0,0.0,100.00,0.00,0.0,100.00,100.00,100.00
NG,0.0,0.00,0.0,0.0,100.00,0.00,0.0,100.00,100.00,100.00
PC,0.0,1.82,0.0,0.0,21.01,0.00,0.0,26.67,21.01,20.51
PCFX,0.0,0.00,0.0,0.0,100.00,0.00,0.0,100.00,100.00,100.00
PS,0.0,0.58,0.0,0.0,86.58,0.00,0.0,83.37,86.58,82.63
PS2,0.0,1.60,0.0,0.0,42.49,0.00,0.0,39.97,42.49,31.48
PS3,0.0,1.85,0.0,0.0,34.39,0.00,0.0,38.60,34.39,28.71
PS4,0.0,0.00,0.0,0.0,34.94,0.00,0.0,36.20,34.94,35.19
PSP,0.0,1.38,0.0,0.0,65.17,0.08,0.0,61.84,65.17,55.00
PSV,0.0,0.23,0.0,0.0,66.44,0.00,0.0,71.72,66.44,64.60
SAT,0.0,0.00,0.0,0.0,100.00,0.00,0.0,100.00,100.00,100.00
SCD,0.0,0.00,0.0,0.0,100.00,0.00,0.0,100.00,100.00,100.00
SNES,0.0,0.00,0.0,0.0,100.00,0.00,0.0,100.00,100.00,100.00
TG16,0.0,0.00,0.0,0.0,100.00,0.00,0.0,100.00,100.00,100.00
WS,0.0,0.00,0.0,0.0,100.00,0.00,0.0,100.00,100.00,100.00
Wii,0.0,2.61,0.0,0.0,57.76,0.00,0.0,55.90,57.76,24.33
WiiU,0.0,0.00,0.0,0.0,31.97,0.00,0.0,38.78,31.97,28.57
X360,0.0,2.50,0.0,0.0,23.58,0.16,0.0,27.32,23.58,16.63
XB,0.0,2.50,0.0,0.0,28.96,0.00,0.0,12.04,28.96,10.97
XOne,0.0,0.00,0.0,0.0,26.69,0.00,0.0,31.87,26.69,24.30

In [18]:
len(df_with_na_share) # общее кол-во платформ

31

In [19]:
len(df_with_na_share[df_with_na_share['critic_score']==100]) # кол-во платформ для которых отсутсвуют оценки критиков и пользователей

14

Пропуски характерны для столбоцов `critic_score` - 51.39%, `user_score` - 40.13, `age_rating` - 40.52, так же пропуски встречаются в столбцах `name` - 0,1%, `year_of_release` - 1.62%, `genre` - 0.01%, `eu_sales` - 0.04, `jp_sales` - `0.02%`, однако их доля не так значительна в сравнении с первыми тремя мною упомянутыми столбцами.

Изучая процент пропусков в разрезе игровых платформ, я пришел к выводу, что пропуски относятся к типу MNAR (missing not at random), то есть пропуски неслучайны, но причину их возникновения, обладая лишь текущими данными, определить не получится. 

Могу лишь обратить внимание на то, что для некоторых игровых платформ полностью отсуствуют данные оценок пользователей, критиков и возрастной рейтинг - таких платформ 14 из 31, что составляет значительную часть. 

Для пропусков в столбцах `critic_score`, `user_score` и `eu_sales` мы найдем средние значения, с учетом платформы игры и и года ее релиза. Пропуски в столбцах `name` и `genre` мы заменим пустой строкой. 

Пропуски для столбоца  `jp_sales` будут удалены, потому что их процент крайне незначителен.
Проспуски в `year_of_release` будут удалены, потому что они помешают фильтрации по годам, а их процент небольшой, заполнить недостающие значения используя имеющиеся данные мы не можем. Пропуски в столбце `age_rating` мы оставим без вниамния, так как эти данные не нужны нам для анализа.

- Обработайте пропущенные значения. Для каждого случая вы можете выбрать оптимальный, на ваш взгляд, вариант: заменить на определённое значение, оставить как есть или удалить.
- Если вы решите заменить пропуски на значение-индикатор, то убедитесь, что предложенное значение не может быть использовано в данных.
- Если вы нашли пропуски в данных с количеством проданных копий игры в том или ином регионе, их можно заменить на среднее значение в зависимости от названия платформы и года выхода игры.

In [20]:
df = df.dropna(subset=['year_of_release'])
df = df.dropna(subset=['jp_sales']) # удаляем строки с просками в годе релиза и продажах в Японии

In [21]:
df[['name','genre']] = df[['name','genre']].fillna(' ') # меняем пропуски в названии игры и названии жанра на пробел

In [22]:
def mean_critic_score(r):
    if pd.isna(r['critic_score']):
        filtred = df[(df['year_of_release'] == r['year_of_release']) & 
                     (df['platform'] == r['platform'])]
        return filtred['critic_score'].mean()
    else: 
        return r['critic_score'] # создаем функцию для подсчета средних значений с учетом года релиза и 
                                 # платформы для оценок критиков    
    
def mean_user_score(r):
    if pd.isna(r['user_score']):
        filtred = df[(df['year_of_release'] == r['year_of_release']) & 
                     (df['platform'] == r['platform'])]
        return filtred['user_score'].mean() 
    else: 
        return r['user_score'] # создаем функцию для подсчета средних значений с учетом года релиза и 
                               # платформы для оценок пользователей
def mean_eu_sales(r):
    if pd.isna(r['eu_sales']):
        filtred = df[(df['year_of_release'] == r['year_of_release']) & 
                     (df['platform'] == r['platform'])]
        return filtred['eu_sales'].mean()
    else: 
        return r['eu_sales'] # создаем функцию для подсчета средних значений с учетом года релиза и 
                             # платформы для продаж в европе
    
df['critic_score'] = df.apply(mean_critic_score, axis=1) 
df['user_score'] = df.apply(mean_user_score, axis=1)
df['eu_sales'] = df.apply(mean_user_score, axis=1) # последовательно применяем функции

In [23]:
round(df.isna().sum() / len(df) * 100, 2) # проверяем результат

name                0.00
platform            0.00
year_of_release     0.00
genre               0.00
na_sales            0.00
eu_sales            7.53
jp_sales            0.00
other_sales         0.00
critic_score        8.87
user_score          7.53
age_rating         40.65
dtype: float64

In [24]:
df = df.dropna(subset=['critic_score'])
df = df.dropna(subset=['user_score'])
df = df.dropna(subset=['eu_sales'])
round(df.isna().sum() / len(df) * 100, 2) # удаляем пропуски, которые не удалось заполнить

name                0.00
platform            0.00
year_of_release     0.00
genre               0.00
na_sales            0.00
eu_sales            0.00
jp_sales            0.00
other_sales         0.00
critic_score        0.00
user_score          0.00
age_rating         35.42
dtype: float64

Мы заменили на средние значения пропуски в столбцах `critic_score`, `user_score` и `eu_sales` и удалили значения, которые не удалось заполнить.

Пропуски в столбцах `name` и `genre` мы замениили пустой строкой, а пропуски в `jp_sales` удалили.

### 2.4. Явные и неявные дубликаты в данных

- Изучите уникальные значения в категориальных данных, например с названиями жанра игры, платформы, рейтинга и года выпуска. Проверьте, встречаются ли среди данных неявные дубликаты, связанные с опечатками или разным способом написания.
- При необходимости проведите нормализацию данных с текстовыми значениями. Названия или жанры игр можно привести к нижнему регистру, а названия рейтинга — к верхнему.

In [25]:
df['platform'].unique() # ищем уникальные названия платформ

array(['Wii', 'DS', 'X360', 'PS3', 'PS2', 'GBA', 'PS4', '3DS', 'PS', 'XB',
       'PC', 'PSP', 'XOne', 'WiiU', 'GC', 'PSV', 'DC'], dtype=object)

In [26]:
df['genre'].unique() #

array(['Sports', 'Racing', 'Platform', 'Misc', 'Simulation', 'Action',
       'Role-Playing', 'Puzzle', 'Shooter', 'Fighting', 'Adventure',
       'Strategy', 'MISC', 'ROLE-PLAYING', 'RACING', 'ACTION', 'SHOOTER',
       'FIGHTING', 'SPORTS', 'PLATFORM', 'ADVENTURE', 'SIMULATION',
       'PUZZLE', 'STRATEGY'], dtype=object)

In [27]:
df['age_rating'].unique() # ищем уникалные значения возрасного рейтинга

array(['E', nan, 'M', 'T', 'E10+', 'K-A', 'AO', 'EC', 'RP'], dtype=object)

In [28]:
df['year_of_release'].unique() # проверяем уникальные года

array(['2006-01-01T00:00:00.000000000', '2008-01-01T00:00:00.000000000',
       '2009-01-01T00:00:00.000000000', '2005-01-01T00:00:00.000000000',
       '2007-01-01T00:00:00.000000000', '2010-01-01T00:00:00.000000000',
       '2013-01-01T00:00:00.000000000', '2004-01-01T00:00:00.000000000',
       '2002-01-01T00:00:00.000000000', '2001-01-01T00:00:00.000000000',
       '2011-01-01T00:00:00.000000000', '2015-01-01T00:00:00.000000000',
       '2012-01-01T00:00:00.000000000', '2014-01-01T00:00:00.000000000',
       '1997-01-01T00:00:00.000000000', '1999-01-01T00:00:00.000000000',
       '2016-01-01T00:00:00.000000000', '2003-01-01T00:00:00.000000000',
       '1998-01-01T00:00:00.000000000', '1996-01-01T00:00:00.000000000',
       '2000-01-01T00:00:00.000000000', '1992-01-01T00:00:00.000000000',
       '1994-01-01T00:00:00.000000000', '1985-01-01T00:00:00.000000000',
       '1988-01-01T00:00:00.000000000'], dtype='datetime64[ns]')

В столбцах `platform` и `year_of_release` неявных дубликатов нет. Однако в столбцах `genre` и `age_rating` они были найдены.

In [29]:
df['age_rating'] = df['age_rating'].replace({
    'K-A':'EC',
    'EС':'EC',
}) # заменяем неявные дубликаты в значениях возрастного рейтинга
df['genre'] = df['genre'].str.lower() # приводим названия жанров к нижнему регистру

In [30]:
df['genre'].unique() # проверяем названия жанров

array(['sports', 'racing', 'platform', 'misc', 'simulation', 'action',
       'role-playing', 'puzzle', 'shooter', 'fighting', 'adventure',
       'strategy'], dtype=object)

In [31]:
df['age_rating'].unique() # проверяем значения возрастного рейтинга

array(['E', nan, 'M', 'T', 'E10+', 'EC', 'AO', 'RP'], dtype=object)

In [32]:
df[(df.duplicated(subset=['name', 'platform', 'year_of_release', 'genre'], keep = False) == True)]
# ищем дублирующиеся строки

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,age_rating
267,Batman: Arkham Asylum,PS3,2009-01-01,action,2.24,8.900000,0.07,0.61,91.000000,8.900000,T
268,Batman: Arkham Asylum,PS3,2009-01-01,action,2.24,8.900000,0.07,0.61,91.000000,8.900000,T
367,James Bond 007: Agent Under Fire,PS2,2001-01-01,shooter,1.90,7.900000,0.10,0.41,72.000000,7.900000,T
368,James Bond 007: Agent Under Fire,PS2,2001-01-01,shooter,1.90,7.900000,0.10,0.41,72.000000,7.900000,T
606,Madden NFL 13,PS3,2012-01-01,sports,2.11,5.500000,0.00,0.23,83.000000,5.500000,E
...,...,...,...,...,...,...,...,...,...,...,...
16799,Transformers: Prime,Wii,2012-01-01,action,0.00,6.660000,0.00,0.00,76.200000,6.660000,NaN
16911,Metal Gear Solid V: The Definitive Experience,XOne,2016-01-01,action,0.01,6.598485,0.00,0.00,73.833333,6.598485,M
16912,Metal Gear Solid V: The Definitive Experience,XOne,2016-01-01,action,0.01,6.598485,0.00,0.00,73.833333,6.598485,M
16939,The Longest 5 Minutes,PSV,2016-01-01,action,0.00,7.776923,0.01,0.00,74.300000,7.776923,NaN
16940,The Longest 5 Minutes,PSV,2016-01-01,action,0.00,7.776923,0.01,0.00,74.300000,7.776923,NaN

In [33]:
df.drop_duplicates(subset=['name', 'platform', 'year_of_release', 'genre'],keep='first', inplace=True)
# удаляем дубликаты

In [34]:
df.duplicated(subset=['name', 'platform', 'year_of_release', 'genre']).sum() 
# проверяем остались ли дубликаты

0

Я применил сначала фильтрацию для вывода строк-дубликатов, затем удалил их и снова проврил их наличие

Мы заменили неявные дубликаты в столбце `age_rating` - "K-A" это устаревшее значение, сейчас используется "EC", в то же время буква "С" в значении рейтинга была кириллистической и мы заменили ее на латинскую.

В столбце `genre` использовался разный регистр для написания названий жанров и мы привели все названия к нижнему регистру.

Так же мы нашли 1 дублирующуеся строку и сотавили для работы только строку, где есть данные о продажах `na_sales` и `other_sales`

- После того как нормализуете данные и устраните неявные дубликаты, проверьте наличие явных дубликатов в данных.

In [35]:
df.shape[0] # определяем размер датафрейма до удаления дубликатов

14970

In [36]:
df.duplicated().sum() # считаем кол-во дубликатов

0

In [37]:
df.drop_duplicates(keep='first', inplace=True) # удаляем дубликаты

In [38]:
df.duplicated().sum() # провряем кол-во дубликатов

0

In [39]:
df_shape_2 = df.shape[0]
df_shape_2 # проверяем размер датафрейма после удаления дубликатов

14970

В датафрейме мы нашли 220 явных дубликатов, до их удаления в датафрейме была 15191 строка, после удаления осталось 14971 строк.

- В процессе подготовки данных вы могли что-либо удалять, например строки с пропусками или ошибками, дубликаты и прочее. В этом случае посчитайте количество удалённых строк в абсолютном и относительном значениях.

In [40]:
cnt_dltd_row = df_shape_1 - df_shape_2
cnt_dltd_row # считаем кол-во удаленных строк

1986

In [41]:
round((cnt_dltd_row / df_shape_1) * 100,2) # считаем процент удаленных строк

11.71

До предобработки у нас было 16956 строк, после завершения пребработки осталось 14970, мы удалили 1985 строк, что ставляет 11.71% от всего объема данных


Мы провели преобработку данных:
- избавились от пропущенных значений, выбрав наиболее подходящие методы - часть данных удалили, часть заменили подходящими средними значениями или значениями-индикаторами
- выявили неявные дубликаты и устранили их
- удалили явные дубликаты

Теперь данные подготовлены для дальнейшего анализа.

---

## 3. Фильтрация данных

Коллеги хотят изучить историю продаж игр в начале XXI века, и их интересует период с 2000 по 2013 год включительно. Отберите данные по этому показателю. Сохраните новый срез данных в отдельном датафрейме, например `df_actual`.

In [42]:
df['year_of_release'] = df['year_of_release'].dt.year # выделяем из даты год

In [43]:
df_actual = df[(df['year_of_release']>1999) & (df['year_of_release']<2014)].copy() # фильтруем данные по годам 
                                                                                   # с 2000 по 2013

Мы создали новый датафрейм, где были отобраны данные с 2000 по 2013 годы включительно.

---

## 4. Категоризация данных
    
Проведите категоризацию данных:
- Разделите все игры по оценкам пользователей и выделите такие категории: высокая оценка (от 8 до 10 включительно), средняя оценка (от 3 до 8, не включая правую границу интервала) и низкая оценка (от 0 до 3, не включая правую границу интервала).

In [44]:
def categorize_games(r):
    if r['user_score'] >= 8:
        return 'Высокая оценка'
    elif r['user_score'] >= 3:
        return 'Средняя оценка'
    else:
        return 'Низкая оценка' # пишем функцию для категоризации данных по оценкам пользователей

In [45]:
df_actual['Category_users_score'] = df_actual.apply(categorize_games, axis=1) # применяем функцию

Мы добавили к отфильтрованным по годам данным новый столбец с категорией по оценкам пользователей.

- Разделите все игры по оценкам критиков и выделите такие категории: высокая оценка (от 80 до 100 включительно), средняя оценка (от 30 до 80, не включая правую границу интервала) и низкая оценка (от 0 до 30, не включая правую границу интервала).

In [46]:
def categorize_games(r):
    if r['critic_score'] >= 80:
        return 'Высокая оценка'
    elif r['critic_score'] >= 30:
        return 'Средняя оценка'
    else:
        return 'Низкая оценка' # пишем функцию для категоризации данных по оценкам критиков

In [47]:
df_actual['Category_critics_score'] = df_actual.apply(categorize_games, axis=1) # применяем функцию

Мы добавили к отфильтрованным по годам данным новый столбец с категорией по оценкам критиков.

- После категоризации данных проверьте результат: сгруппируйте данные по выделенным категориям и посчитайте количество игр в каждой категории.

In [48]:
df_actual.groupby('Category_critics_score')['critic_score'].count() # группируем данные и считаем кол-во игр 
                                                                    # для категорий по оценкам критиков

Category_critics_score
Высокая оценка     1756
Низкая оценка        55
Средняя оценка    10717
Name: critic_score, dtype: int64

In [49]:
df_actual.groupby('Category_users_score')['user_score'].count() # группируем данные и считаем кол-во игр 
                                                                # для категорий по оценкам пользвателей

Category_users_score
Высокая оценка     2356
Низкая оценка       115
Средняя оценка    10057
Name: user_score, dtype: int64

Мы подчитали кол-во игр в каждой категории.

- Выделите топ-7 платформ по количеству игр, выпущенных за весь актуальный период.

In [50]:
df_actual.groupby('platform')['name'].count().sort_values(ascending= False).head(7) # считаем кол-во игр для каждой 
                                                                                    # платформы и выделяем топ-7

platform
PS2     2120
DS      2111
Wii     1263
X360    1119
PS3     1086
PSP     1073
GBA      804
Name: name, dtype: int64

Мы нашли топ-7 платформ по количеству выпущенных на них игр.

## 5. Итоговый вывод

Нами были загружены данные датасета `/datasets/new_games.csv`, в котором были представлены данные о продажах и оценках игр.

При знакомстве с данными и их предобработке мы заменили стиль написания названий столбоцов на "snake case", затем были обнаружены и заменены неверные типы данных в столбцах:

- `year_of_release` - float64 на datetime64
- `eu_sales - object` на int64
- `jp_sales - object` на int64
- `user_score - object` на float64

Затем мы применили методы для обработки пропусков в столбцах:
- `name` - пропуски были заменены на значение индикатор - пробел
- `year_of_release` - пропуски были удалены
- `genre` - пропуски были заменены на значение индикатор - пробел
- `critic_score` - большую часть пропусков заменили на средние значения, а там, где это не удалось пропуски были удалены 
- `user_score` - большую часть пропусков заменили на средние значения, а там, где это не удалось пропуски были удалены 
- `age_rating` - пропуски были пропущены, так как эти данные не нужны нам для анализа
- `eu_sales` - пропуски заменили на средние значения
- `jp_sales` - пропуски удалили, так как они составляли незначительную часть

Затем мы обработали неявные дубликаты - в столбце `genre` мы привели все названия жанров к нижнему регистру, а в столбце `age_rating` заменили устаревшее значения рейтинга на актуальное и заменили значение, в котором использовалась кириллистическая "С" на написание латиницой.

Так же мы нашли строку, которая дублировалась почти полностью за исключением `na_sales` и `other_sales` и удалили дубликат.

Данные с явными дубликатами мы нашли и удалили.

После обработки было удалено 11.71% данных.

Когда данные были обработаны мы отфильтровали их по требуемым годам (2000-2013) и добавили столбцы с категориями по оценкам пользователей и критиков:
- `Category_critics_score` - категории на основе оценок критиков
- `Category_users_score` - категории на основе оценок пользователей

Мы подсчитали количество игр в разрезе кажой категории.

Затем мы выделили топ-7 платформ по количеству выпущенных на них игр.